package tutorial

import "learn_future/internal/types"

var TopicsEN = map[string]*types.TutorialCard{
	TopicPerpetualIntro: {
		ID:       TopicPerpetualIntro,
		Title:    "What is a Perpetual Contract?",
		Content:  "A perpetual contract is a derivative with no expiry date — you can hold it indefinitely. It uses a \"funding rate\" mechanism to anchor the contract price to the spot price.\n\nSimply put: you don't need to actually buy BTC. You just bet on whether BTC goes up or down. Guess right and you profit the difference; guess wrong and you lose it.",
		Example:  "BTC is at 60,000 USDT. You think it will rise → open long → BTC rises to 65,000 → you profit 5,000 USDT (without owning BTC)",
		ShowOnce: true,
	},
	TopicLeverage: {
		ID:       TopicLeverage,
		Title:    "What is Leverage?",
		Content:  "Leverage lets you control a larger position with less margin. 10x leverage means 100 USDT margin controls a 1,000 USDT position. Leverage amplifies both gains and losses — higher leverage means closer to liquidation.",
		Formula:  "Margin = Position Value / Leverage",
		Example:  "100 USDT × 10x leverage = control 1,000 USDT position",
		ShowOnce: true,
	},
	TopicLongShort: {
		ID:       TopicLongShort,
		Title:    "Long & Short",
		Content:  "Long (buy) = bullish, profit when price rises, lose when it falls. Short (sell) = bearish, profit when price falls, lose when it rises. The core advantage of futures is the ability to trade both directions.",
		Example:  "BTC at 60,000. Think it will rise → go long. Think it will fall → go short.",
		ShowOnce: true,
	},
	TopicUnrealizedPnl: {
		ID:       TopicUnrealizedPnl,
		Title:    "Unrealized PnL",
		Content:  "Unrealized PnL is your floating profit/loss on open positions. It only becomes real (realized PnL) when you close the position. It changes in real-time with price movement.",
		Formula:  "Unrealized PnL = (Current Price - Entry Price) × Quantity × Direction",
		Example:  "Long 0.01 BTC at 60,000, current 65,000 → PnL = (65000-60000)×0.01×1 = +50 USDT",
		ShowOnce: true,
	},
	TopicTPSL: {
		ID:       TopicTPSL,
		Title:    "Take Profit & Stop Loss",
		Content:  "Take Profit (TP) and Stop Loss (SL) are preset auto-close prices — core risk management tools. TP locks in profit, SL limits loss. Always set a stop loss for every trade.",
		Example:  "Long at 60,000, set TP at 65,000 (take 5,000 profit), SL at 58,000 (max 2,000 loss)",
		ShowOnce: true,
	},
	TopicFundingRate: {
		ID:       TopicFundingRate,
		Title:    "Funding Rate",
		Content:  "Funding rate is settled every 8 hours (00:00/08:00/16:00 UTC) to anchor the contract price to spot. When positive, longs pay shorts; when negative, shorts pay longs.",
		Formula:  "Funding Fee = Position Value × Funding Rate",
		Example:  "Position value 10,000 USDT, rate 0.01% → Fee = 10,000 × 0.0001 = 1 USDT",
		ShowOnce: true,
	},
	TopicLiquidation: {
		ID:       TopicLiquidation,
		Title:    "Liquidation",
		Content:  "When your margin ratio drops below 0.5%, the system force-closes your position (liquidation). Higher leverage means the liquidation price is closer to entry. Use reasonable leverage and always set stop losses.",
		Formula:  "Liq Price (long) = Entry × (1 - 1/Leverage + 0.5%)\nMargin Ratio = (Margin + Unrealized PnL) / Position Value",
		Example:  "Long at 60,000, 10x leverage → liq price ≈ 54,300, a 9.5% drop triggers liquidation",
		ShowOnce: true,
	},
	TopicPostLiquidation: {
		ID:       TopicPostLiquidation,
		Title:    "Post-Liquidation Review",
		Content:  "Your position was liquidated — you lost all the margin. This is the most painful trading experience, but also the best lesson. Tips: 1) Lower leverage 2) Always set stop loss 3) Don't put all funds in one trade.",
		ShowOnce: false,
	},
	TopicForceTpADL: {
		ID:       TopicForceTpADL,
		Title:    "Force TP & ADL",
		Content:  "Your position's profit triggered the counterparty LP's risk limit, resulting in forced take-profit. In live trading, this corresponds to Auto-Deleveraging (ADL). Market makers set max exposure limits; when one side's profit gets too large, ADL is triggered. ADL prioritizes deleveraging the most profitable counterparty positions.",
		Formula:  "Force TP trigger: ROI ≥ 500% (position value reaches 6× margin)",
		Example:  "10x leverage long, price rises 50% → ROI = 500%, force TP triggered",
		ShowOnce: false,
	},
	TopicRealizedPnl: {
		ID:       TopicRealizedPnl,
		Title:    "Realized PnL",
		Content:  "The actual profit/loss after closing, minus fees and accumulated funding. This is the real money you earned or lost.",
		Formula:  "Price PnL = (Close - Entry) × Qty × Direction\nRealized PnL = Price PnL - Close Fee\nNet PnL = Realized PnL + Cumulative Funding",
		Example:  "Price PnL +500 - Fee 0.4 = Realized 499.6 + Funding -1 = Net 498.6 USDT",
		ShowOnce: true,
	},
	TopicMarketOrder: {
		ID:       TopicMarketOrder,
		Title:    "Market Order",
		Content:  "A market order executes immediately at the current market price. Guarantees execution but may have slippage during high volatility. Best for quick entry.",
		Example:  "BTC at 60,000, place market long → fills immediately at ~60,000",
		ShowOnce: true,
	},
	TopicLimitOrder: {
		ID:       TopicLimitOrder,
		Title:    "Limit Order",
		Content:  "A limit order only fills when price reaches your specified level. Better price but may not fill. Margin is frozen while the order is pending.",
		Example:  "BTC at 60,000, you want to buy at 58,000 → place limit long at 58,000, auto-fills when price drops to 58,000",
		ShowOnce: true,
	},
	TopicTradingFee: {
		ID:       TopicTradingFee,
		Title:    "Trading Fees",
		Content:  "Fees are charged on both open and close, calculated as a percentage of position value. Frequent trading accumulates fees that eat into profits.",
		Formula:  "Fee = Position Value × Rate (0.04%)",
		Example:  "Position value 1,000 USDT → Fee = 1,000 × 0.04% = 0.4 USDT (open + close = 0.8 USDT total)",
		ShowOnce: true,
	},
	TopicMarginMode: {
		ID:       TopicMarginMode,
		Title:    "Isolated vs Cross Margin",
		Content:  "Isolated: Each position has independent margin. Liquidation only loses that position's margin. Best for beginners.\n\nCross: All positions share account balance as margin. Harder to liquidate but if it happens, you lose everything. Best for experienced traders.",
		Formula:  "Isolated: Position margin ratio ≤ 0.5% → liquidated\nCross: Account equity ≤ Total maintenance margin → all liquidated",
		Example:  "Account 1,000 USDT, two positions at 100 each. Isolated: max loss 100 per position. Cross: could lose all 1,000.",
		ShowOnce: true,
	},
}
